
services:
  twitch2discord-bridge:
    logging:
      options:
        max-size: 500m
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ./${TAG:-config}.yaml:/app/config.yaml:z

    restart: always
    image: twitch2discord-bridge
    container_name: t2d_${TAG:-bot}
    
