name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: general-server

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cp ~/configs/* .
